export enum Status {
  BEFORE_DEPOSITE = "BEFORE_DEPOSITE",
  AFTER_DEPOSITE = "AFTER_DEPOSITE",
  BEFORE_SPIN = "BEFORE_SPIN",
  AFTER_SPIN = "AFTER_SPIN",
}

// export const BE_WALLET_KP =
//   "4F1PtAfoFPJzMUbn7ZkeCKwATdQHbZvYnNwA5b8TM9CPb14VWDN29drVaPno2PQN8NACNbXbjnXWsMcZ6ANDruUP";
// export const BE_PUBKEY = "gfgkqDfAGLW3qBSq6Gmx2UhbxMqRCc4YiCgNY14dAVZ";
export const BE_WALLET_KP =
  "3Q7yqFgy5sBgRbpV3cuCbgCroUexwebP3HWLaN5MMCWXdSZmnNPpBHQeLjW2Qwwccshncs8n8NPSBft5mma5RhwB";
export const BE_PUBKEY = "F2vhKcF1GpmNdmxrw7z1Ct9S1L26s5Xs5ne92VjyKb8R";
export const MINT = "AmgUMQeqW8H74trc8UkKjzZWtxBdpS496wh4GLy2mCpo";
export const TOKEN_ACCOUNT_ADDRESS = "ELuGXJp8kA4jhn7cnyHaRkviBFtTCdMq3S1CgC7U9TvM";
export const USERWALLETADDRESS="4pY6apD1FyMLGXWYJtHmm5QagzkzJWFznx8wHguHPQji";